### ISSUE TITLE
Infinite falling

### ISSUE THREAD

**Issue by tearystarz** [Danimation2001/Postway-Pass_Game#16]
**Level**
- Which level does this bug occur?
Level 2 Demo (Winter Level)

**Describe the bug**

In some areas there's ways to fall out of the map resulting in infinite falling. One area is located at a small hidden cave where one of the mail is hidden I clipped through the corner of the cave and fell out of the map. Another area with this issue is at the beginning of the level behind where the player spawns where the mountain and boulders are connected, there's a gap in which you can fall in inside and then fall outside of the map.

**To Reproduce**
1. Go to the path behind where you spawn up to a small ramp where you'll seen a piece of mail
2. Behind the trees fall between the boulders and mountain
3. You will slide inside of the said mountain and boulders in a levitated state, keeping moving on your left

**Expected behavior**
Player should not be clipping outside of the map resulting in infinite falling.

**Screenshots**
![image](https://user-images.githubusercontent.com/101615171/192130278-d719e213-cca6-4a0d-aadc-37b860d23a3c.png)
![fall_3](https://user-images.githubusercontent.com/62206263/192128670-102a2174-3250-4ace-8364-0d9de69385af.png)
![fall_2](https://user-images.githubusercontent.com/62206263/192128674-38434b30-668e-4f0b-ab50-2f30647cc2d0.png)
![fall](https://user-images.githubusercontent.com/62206263/192128679-4de17f5c-a4ae-4af1-89ef-5ecd39a18938.png)

**Desktop System**

- OS: Windows 11

**Comment by jellysnoms** [comment]
- fixed the gaps related to invisible walls on the edges of the map which caused players to fall through or get stuck
- fixed barriers at spawn point to prevent unintended sliding/levitating
- fixed the infinite falling bug in the cave. It was an oversight of not repositioning a teleport destination after raising terrain, causing players to teleport under the terrain and fall through the map
